// apps/nominations/views/login.vue
<template>
  <auth-layout>
    <div class="login-box" id="login-box">
      <flash-message>{{flash}}</flash-message>
      <div class="header">
        <i class="fa fa-sign-in"></i> Sign-in
      </div>
      <form id="login" name="login" method="post" action="login">
        <div class="body">
          <!-- TODO: include errors.validation -->
          <div class="form-group has-feedback">
            <label for="email">Email Address</label>
            <input class="form-control" name="email" type="text" />
            <i class="fa fa-envelope form-control-feedback"></i>
          </div>
          <div class="form-group has-feedback">
            <label for="password">Password</label>
            <input class="form-control" name="password" type="password" />
            <i class="fa fa-lock form-control-feedback"></i>
          </div>
          <div class="form-group">
            <input type="checkbox" /> Remember me
          </div>
        </div>
        <div class="footer">
          <input class="btn bg-auth btn-block btn-flat" type="submit" value="Sign In" />
          <!-- TODO: forgot email -->
          <div class="col-xs-6">
            <a class="btn btn-link pull-right" href="/register">
              <i class="fa fa-user-plus"></i> Register
            </a>
          </div>
        </div>
      </form>
    </div>
  </auth-layout>
</template>

<script>
  module.exports = {props: {flash: {default: ''}}};
</script>

<style></style>

// react-ui/src/app/auth/login.js
// @flow

import * as React from 'react';
import { Redirect } from 'react-router';
import styled from 'styled-components';
import FooterLink from './components/footer-link';

import FormBox from './components/form-box';

import { AuthToken } from '../../lib/auth';
import Footer from './components/footer';
import FormGroup from './components/form-group';
import Label from './components/form-label';
import querystring from 'querystring';

const Icon = styled.i`top: 20px !important;`;

export default class Login extends React.Component<{
  history: *,
  location: *,
  returnTo: ?string
}> {
  box: ?FormBox;
  justRegistered: boolean;

  componentDidMount() {
    const params = querystring.parse(this.props.location.search);
    console.log('ohey', params);
    if (params['?justRegistered'] && (params['?justRegistered'] === 'true' || params['?justRegistered'] === true)) {
      (this.box).flashErrorMessage('Check your email to continue the registration process.');
    }
  }

  render(): React.Node {

    if (!AuthToken.expired()) {
      return <Redirect to="/dashboard" />;
    }
    return (
      <FormBox
        title="Log in"
        submitText="Login"
        headerImageClass="fa fa-sign-in"
        onSubmit={this.onSubmit.bind(this)}
        ref={ref => (this.box = ref)}
        body={
          <div>
            <FormGroup className="form-group has-feedback">
              <Label>
                E-mail address
                <input className="form-control" name="email" type="text" />
              </Label>
              <Icon className="fa fa-envelope form-control-feedback" />
            </FormGroup>
            <FormGroup className="form-group has-feedback">
              <Label>
                Password
                <input className="form-control" name="password" type="password" />
              </Label>
              <Icon className="fa fa-lock form-control-feedback" />
            </FormGroup>
          </div>
        }
        footer={
          <Footer>
            <div className="col-xs-6">
              <FooterLink className="btn btn-link" to="/auth/recover">
                <i className="fa fa-lock" />
                <span> Forgot Password</span>
              </FooterLink>
            </div>
            <div className="col-xs-6">
              <FooterLink className="btn btn-link pull-right" to="/auth/register">
                <i className="fa fa-user-plus" />
                <span> Register</span>
              </FooterLink>
            </div>
          </Footer>
        }
      />
    );
  }

  async onSubmit({ email, password }: { email: string, password: string }): Promise<void> {
    try {
      const success = await AuthToken.login(email, password);
      if (success) {
        this.props.history.replace(
          this.props.location.state != null && this.props.location.state.from != null
            ? this.props.location.state.from
            : '/dashboard');
      } else {
        (this.box: any).flashErrorMessage('Login failed: wrong email or password');
      }
    } catch (exc) {
      (this.box: any).flashErrorMessage('Login failed: unknown error');
      console.log('Error logging in:', exc);
    }
  }
}
