// react-ui/src/app/auth/register.js
// @flow

import * as React from 'react';
import styled from 'styled-components';

import FormBox from './components/form-box';

import Footer from './components/footer';
import FooterLink from './components/footer-link';
import FormGroup from './components/form-group';
import Label from './components/form-label';

import { getAffiliationList } from '../../api/affiliation';
import { register } from '../../lib/auth';

const Icon = styled.i`top: 20px !important;`;

export default class Register extends React.Component <{
  history: *
}, *> {

  box: ?FormBox;

  AFFILIATION_PLACEHOLDER: string;

  state: {
    affiliationItems: Array<{}>,
    affiliationList: Array<React.Node>
  };

  constructor() {
    super();
    this.AFFILIATION_PLACEHOLDER = '=== Select affiliation ===';
    this.state = {
      affiliationItems: [],
      affiliationList: []
    };
  }

  async fetch(): Promise<void> {
    const response: Object = await getAffiliationList();
    if (response.items == null || response.items === '' || response.items === undefined) {
      throw new Error('items not defined');
    }
    this.setState({ affiliationItems: response.items });
    return Promise.resolve();
  }

  async setAffiliationList(): Promise<void> {
    let affiliationList;
    try {
      await this.fetch();
      const items: Array<Object> = this.state.affiliationItems;
      affiliationList = items.map(item =>
        <option key={item.id} value={item.id}>{item.type.toUpperCase()} - {item.name}</option>
      );
    } catch (err) {
      console.error(err);
      this.flashErrorMessage('Error: could not get affiliation list from server');
      return;
    }

    this.setState({ affiliationList: affiliationList });
    return Promise.resolve();
  }

  componentDidMount() {
    this.setAffiliationList();
  }

  render(): React.Node {
    return (
      <FormBox
        title="Register"
        submitText="Register"
        headerImageClass="fa fa-user-plus"
        onSubmit={this.onSubmit.bind(this)}
        ref={ref => (this.box = ref)}
        body={
          <div>
            <FormGroup className="form-group has-feedback">
              <Label>
                First Name
                <input className="form-control" name="name_first" type="text" />
              </Label>
            </FormGroup>
            <FormGroup className="form-group has-feedback">
              <Label>
                Last Name
                <input className="form-control" name="name_last" type="text" />
              </Label>
            </FormGroup>
            <FormGroup className="form-group has-feedback">
                <Label>
                  Affiliation
                  <select className="form-control" name="affiliation_id" type="text" >
                    <option>{this.AFFILIATION_PLACEHOLDER}</option>
                    {this.state.affiliationList}
                  </select>
                </Label>
            </FormGroup>
            <FormGroup className="form-group has-feedback">
              <Label>
                Rank
                <input className="form-control" name="rank" type="text" />
              </Label>
            </FormGroup>
            <FormGroup className="form-group has-feedback">
              <Label>
                Phone
                <input className="form-control" name="phone" type="text" />
              </Label>
              <Icon className="fa fa-phone form-control-feedback" />
            </FormGroup>
            <FormGroup className="form-group has-feedback">
              <Label>
                E-mail address
                <input className="form-control" name="email" type="text" />
              </Label>
              <Icon className="fa fa-envelope form-control-feedback" />
            </FormGroup>
            <FormGroup className="form-group has-feedback">
              <Label>
                Password
                <input className="form-control" name="password" type="password" />
              </Label>
              <Icon className="fa fa-lock form-control-feedback" />
            </FormGroup>
            <FormGroup className="form-group has-feedback">
              <Label>
                Confirm Password
                <input className="form-control" name="password_confirm" type="password" />
              </Label>
              <Icon className="fa fa-lock form-control-feedback" />
            </FormGroup>
          </div>
        }
        footer={
          <Footer>
            <div className="col-xs-6">
              <FooterLink className="btn btn-link" to="/auth/login">
                <i className="fa fa-sign-in" />
                <span> Login</span>
              </FooterLink>
            </div>
            <div className="col-xs-6">
            </div>
          </Footer>
        }
      />
    );
  }

  async onSubmit({
    name_first,
    name_last,
    affiliation_id,
    rank, phone, email,
    password,
    password_confirm
  }: {
    name_first: string,
    name_last: string,
    affiliation_id: number,
    rank: string,
    phone: number,
    email: string,
    password: string,
    password_confirm: string
  }): Promise<void> {
    const validName = name => name != null && name !== '' && name.match('[a-zA-Z.-]{2,}');
    let error = null;
    if (!validName(name_first)) {
      error = 'First Name must be at least two characters and only contain letters, dashes, or periods';
    } else if (!validName(name_last)) {
      error = 'Last Name must be at least two characters and only contain letters, dashes, or periods';
    } else if (affiliation_id === this.AFFILIATION_PLACEHOLDER) {
      error = 'Affiliation is required';
    } else if (phone == null || phone === '') {
      error = 'Phone number is required';
    } else if (email == null || email === '' || !email.match('[a-zA-Z.-]{2,}')) {
      error = 'Email is required, and must be in email address format (text@text.domain)';
    } else if (password == null || password === '') {
      error = 'Password is required';
    } else if (password_confirm == null || password_confirm === '') {
      error = 'Password confirmation is required';
    } else if (password !== password_confirm) {
      error = 'Passwords do not match';
    }

    if (error != null) {
      this.flashErrorMessage(error);
      return;
    }

    try {
      const result = await register(name_first, name_last, rank, affiliation_id, email, password);
      if (result.success) {
        this.props.history.replace('/auth/login?justRegistered=true');
      } else {
        this.flashErrorMessage(result.error);
      }
    } catch (exc) {
      console.error(exc);
      this.flashErrorMessage('Registration failed: unknown error');
    }
  }

  flashErrorMessage(msg: string) {
    if (this.box != null) {
      this.box.flashErrorMessage(msg);
    }
  }
}

// views/register.vue
<template>
  <auth-layout>
    <div class="container">
      <div class="login-box" id="login-box">
        <p>{{flash}}</p>
        <div class="header">
            <i class="fa fa-user-plus"></i> Register
        </div>
      <form id="signup" name="register" method="post" action="/register">
        <div class="body">
            <!-- TODO: include errors.validation -->
            <div class="form-group has-feedback">
              <label for="firstname">First Name</label>
              <input class="form-control" name="firstname" type="text" />
              <i class="fa form-control-feedback"></i>
            </div>
            <div class="form-group has-feedback">
              <label for="lastname">Last Name</label>
              <input class="form-control" name="lastname" type="text" />
              <i class="fa form-control-feedback"></i>
            </div>
            <div class="form-group has-feedback">
              <label for="affiliation">Affiliation</label>
              <select class="form-control" name="affiliation">
                <option value="" disabled hidden>=== Select affiliation ===</option>
                <option v-for="affiliate in affiliation" v-bind:value="affiliate.id">
                  {{ affiliate.type.toUpperCase() }} - {{ affiliate.name }}
                </option>
            </select>
              <i class="fa form-control-feedback"></i>
            </div>
            <div class="form-group has-feedback">
              <label for="rank">Rank</label>
              <input class="form-control" name="rank" type="text" />
              <i class="fa form-control-feedback"></i>
            </div>
            <div class="form-group has-feedback">
              <label for="phone">Phone</label>
              <input class="form-control" name="phone" type="tel" />
              <i class="fa fa-phone form-control-feedback"></i>
            </div>
            <div class="form-group has-feedback">
              <label for="email">Email Address</label>
              <input class="form-control" name="email" type="email" />
              <i class="fa fa-envelope form-control-feedback"></i>
            </div>
            <div class="form-group has-feedback">
              <label for="password">Password</label>
              <input class="form-control" name="password" type="password" autocomplete="off" />
              <i class="fa fa-lock form-control-feedback"></i>
            </div>
            <div class="form-group has-feedback">
              <label for="password_confirmation">Confirm Password</label>
              <input class="form-control" name="password_confirmation" type="password" autocomplete="off" />
              <i class="fa fa-lock form-control-feedback"></i>
            </div>
            <div class="form-group has-feedback">
                <!-- TODO: Add Recaptcha -->
            </div>
        </div>

        <div class="footer">
            <input class="btn bg-auth btn-block btn-flat" type="submit" value="Register" />
            <hr/>
            <div class="row">
                <div class="col-xs-6">
                    <a class="btn btn-link" href="/login"> <i class="fa fa-sign-in"></i>Login</a>
                </div>
            </div>
        </div>
      </form>
    </div>
</div>
  </auth-layout>
</template>

<script>
  module.exports = {
      props: {affiliation: {required: true}, flash: {default: ''}},
      components: {'auth-layout': require('./layouts/auth.vue')}
  };
</script>

<style>
</style>
