// apps/nominations/views/login.vue
<template>
  <auth-layout>
    <div class="login-box" id="login-box">
      <flash-message>{{flash}}</flash-message>
      <div class="header">
        <i class="fa fa-sign-in"></i> Sign-in
      </div>
      <form id="login" name="login" method="post" action="login">
        <div class="body">
          <!-- TODO: include errors.validation -->
          <div class="form-group has-feedback">
            <label for="email">Email Address</label>
            <input class="form-control" name="email" type="text" />
            <i class="fa fa-envelope form-control-feedback"></i>
          </div>
          <div class="form-group has-feedback">
            <label for="password">Password</label>
            <input class="form-control" name="password" type="password" />
            <i class="fa fa-lock form-control-feedback"></i>
          </div>
          <div class="form-group">
            <input type="checkbox" /> Remember me
          </div>
        </div>
        <div class="footer">
          <input class="btn bg-auth btn-block btn-flat" type="submit" value="Sign In" />
          <!-- TODO: forgot email -->
          <div class="col-xs-6">
            <a class="btn btn-link pull-right" href="/register">
              <i class="fa fa-user-plus"></i> Register
            </a>
          </div>
        </div>
      </form>
    </div>
  </auth-layout>
</template>

<script>
  module.exports = {props: {flash: {default: ''}}};
</script>

<style></style>

// frontend/applications/nominations/src/app/pages/Login/Login.tsx
import * as React from 'react';
import { Redirect } from 'react-router';
import styled from 'styled-components';

import FooterLink from '../../auth/components/footer-link';

import FormBox from '../../auth/components/form-box';

import Footer from '../../auth/components/footer';
import FormGroup from '../../auth/components/form-group';
import Label from '../../auth/components/form-label';
import firebase from '../../../services/auth';
const Icon = styled.i`
  top: 20px !important;
`;

export default class Login extends React.Component {
  render() {
    return (
      <FormBox
        title="Log in"
        submitText="Login"
        headerImageClass="fa fa-sign-in"
        onSubmit={this.onSubmit.bind(this)}
        body={
          <div>
            <FormGroup className="form-group has-feedback">
              <Label>
                E-mail address
                <input className="form-control" name="email" type="text" />
              </Label>
              <Icon className="fa fa-envelope form-control-feedback" />
            </FormGroup>
            <FormGroup className="form-group has-feedback">
              <Label>
                Password
                <input className="form-control" name="password" type="password" />
              </Label>
              <Icon className="fa fa-lock form-control-feedback" />
            </FormGroup>
          </div>
        }
        footer={
          <Footer>
            <div className="col-xs-6">
              <FooterLink className="btn btn-link" to="/auth/recover">
                <i className="fa fa-lock" />
                <span> Forgot Password</span>
              </FooterLink>
            </div>
            <div className="col-xs-6">
              <FooterLink className="btn btn-link pull-right" to="/auth/register">
                <i className="fa fa-user-plus" />
                <span> Register</span>
              </FooterLink>
            </div>
          </Footer>
        }
      />
    );
  }

  async onSubmit({ email, password }) {
    try {
      firebase.auth().signInWithEmailAndPassword(email, password);
    } catch (exc) {
      alert('Login failed: wrong email or password');
      console.log('Error logging in:', exc);
    }
  }
}
